name: Check 🧐
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/import_map*json') }}
      - run: find . -type f \( -iname \*.tsx -o -iname \*.ts \) -exec deno cache --import-map import_map_test.json {} +
      - run: deno task test
      - run: deno task check
      - run: deno task lint
